import React, { ReactNode } from 'react'
import Head from 'next/head'
import { useSession, signOut } from 'next-auth/react'
import Image from 'next/image'
import Default from '@/utils/default.json'

interface LayoutProps {
  children?: ReactNode
}

interface Default {
  head: {
    title: string
    favicon: {
      rel: string
      href: string
    }
  }
  logo: string
  log_out: string
}

export default function Layout({ children }: LayoutProps = {}) {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        {/* Title */}
        <title>{Default.head["'title"]}</title>
        {/* Favicon */}
        <link rel={Default.head.favicon.rel} href={Default.head.favicon.href} />
        {/* Description */}
        <meta name="description" content="Generated by create next app" />
        {/* Before, React was automatically inserting the following in the <head> but with SSR the responsibility moved to the developer to add this bit themselves. */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <nav className="py-16 m-auto flex flex-row justify-between px-3 md:px-7 max-w-5xl relative">
        <h1 className="text-sm md:text-4xl font-extrabold font-russo cursor-pointer text-tl-primary">
          {Default.logo}
        </h1>
        {/* Log out button */}
        {session && (
          <button
            type="button"
            className="text-tl-primary cursor-pointer font-extrabold font-russo text-sm md:text-base"
            onClick={() => signOut()}
          >
            {Default.log_out}
          </button>
        )}
      </nav>
      <main
        className="m-auto px-3 md:px-7 max-w-5xl relative z-10"
        style={{ minHeight: '60vh' }}
      >
        {children}
      </main>
      <footer>
        <a
          href={Default.footer.href}
          target="_blank"
          rel="noopener noreferrer"
          className="pb-16 w-full flex justify-center"
        >
          <div className="w-28 h-28 md:w-32 md:h-32 absolute">
            <Image
              src={Default.footer.src}
              alt={Default.footer.alt}
              className="object-contain"
              fill
              sizes="33vw"
            />
          </div>
        </a>
      </footer>
    </>
  )
}
